name: Build APK

on:
  push:
    branches:
      - main  # Cambia esto si tu rama se llama "principal"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: fanygisa-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
Activar workflow para compilar APK
